#!/usr/bin/env python3
"""
Test Hamiltonian constraint satisfaction in TOV initial data.

This test verifies that the initial data generated by create_initial_data_interpolated()
satisfies the Hamiltonian constraint of general relativity before evolution begins.

IMPORTANT: This test analyzes constraints ONLY in the interior region, excluding
ghost cells. Ghost cells (indices 0-2 and -3:-1) may have r<0 or r>r_max and are
not used for physical validation.
"""

import numpy as np
import sys

# Add repository to path
sys.path.insert(0, '/home/yo/repositories/engrenage')

from source.core.grid import Grid
from source.core.spacing import LinearSpacing, NUM_GHOSTS
from source.core.statevector import StateVector
from source.backgrounds.sphericalbackground import FlatSphericalBackground
from source.matter.perfect_fluid import PerfectFluid
from source.matter.hydro.eos import IdealGasEOS
from source.matter.hydro.atmosphere import AtmosphereParams

from examples.TOV.tov_solver import TOVSolver
import examples.TOV.tov_initial_data_interpolated as tov_id
from source.bssn.constraintsdiagnostic import get_constraints_diagnostic


def test_tov_initial_hamiltonian_constraint():
    """
    Verify that TOV initial data satisfies the Hamiltonian constraint.

    This test replicates the exact workflow of TOVEvolution.py for creating
    initial data, then verifies that the Hamiltonian constraint is satisfied
    in the interior region (excluding ghost cells).

    Regions analyzed:
    - Deep interior (NUM_GHOSTS <= i, r < 0.9R): |Ham| should be small
    - Near surface (0.9R < r < 1.1R): allow larger interpolation errors
    - Exterior (r > 1.1R): |Ham| ~ 0 (Schwarzschild vacuum)
    - **EXCLUDED**: Ghost cells (i < NUM_GHOSTS or i >= N-NUM_GHOSTS)

    Expected behavior:
    - Interior: |Ham| < 0.1 (allows truncation + interpolation errors)
    - Exterior: |Ham| < 1e-10 (essentially zero)

    Failure indicates problems in:
    - TOV equation solving
    - TOV → grid interpolation
    - ADM → BSSN conversion
    - Numerical derivatives
    """

    # ========================================================================
    # SETUP - Replicate TOVEvolution.py workflow
    # ========================================================================

    print("\n" + "="*70)
    print("TEST: HAMILTONIAN CONSTRAINT IN TOV INITIAL DATA")
    print("="*70)

    # TOV parameters (SAME as TOVEvolution.py production run)
    Gamma = 2.0
    K = 1.0
    rho_central = 0.128
    num_points = 500  # Full resolution as in production
    r_max = 16.0

    print(f"\nTOV parameters:")
    print(f"  Gamma (γ) = {Gamma}")
    print(f"  K         = {K}")
    print(f"  ρ_c       = {rho_central}")

    # Create grid (SAME as TOVEvolution.py line 639)
    spacing = LinearSpacing(num_points, r_max)
    eos = IdealGasEOS(gamma=Gamma)
    atmosphere = AtmosphereParams()
    hydro = PerfectFluid(eos=eos, spacetime_mode='dynamic', atmosphere=atmosphere)
    state_vec = StateVector(hydro)
    grid = Grid(spacing, state_vec)
    background = FlatSphericalBackground(grid.r)

    print(f"\nGrid configuration:")
    print(f"  N total     = {grid.N} points")
    print(f"  NUM_GHOSTS  = {NUM_GHOSTS}")
    print(f"  N interior  = {grid.N - 2*NUM_GHOSTS} points")
    print(f"  r range     = [{grid.r[0]:.6f}, {grid.r[-1]:.6f}]")
    print(f"  dr          = {grid.min_dr:.6f}")
    print(f"  Ghost cells = r[0:{NUM_GHOSTS}] = {grid.r[:NUM_GHOSTS]}")

    # ========================================================================
    # SOLVE TOV AND CREATE INITIAL DATA
    # ========================================================================

    print(f"\nSolving TOV equations...")

    # Solve TOV (same as TOVEvolution.py lines 628-633)
    tov_solver = TOVSolver(K=K, Gamma=Gamma)
    tov_solution = tov_solver.solve(rho_central, r_max=r_max)

    R = float(tov_solution['R'])
    M = float(tov_solution['M_star'])
    C = M / R

    print(f"  M = {M:.6f}")
    print(f"  R = {R:.6f}")
    print(f"  C = M/R = {C:.6f}")

    # Create initial data (same as TOVEvolution.py lines 640-644)
    print(f"\nCreating initial data (interpolation order 11)...")
    initial_state_2d = tov_id.create_initial_data_interpolated(
        tov_solution, grid, background, eos,
        atmosphere=atmosphere,
        interp_order=11
    )

    print(f"  Initial data shape: {initial_state_2d.shape}")
    print(f"  Note: Ghosts already filled by create_initial_data_interpolated()")
    print(f"        (line 473: grid.fill_boundaries() was called)")

    # ========================================================================
    # COMPUTE HAMILTONIAN CONSTRAINT
    # ========================================================================

    print(f"\nComputing Hamiltonian constraint...")

    # Set background for hydro (needed by get_emtensor)
    hydro.background = background

    # Compute constraints (same as TOVEvolution.py line 647 diagnostic)
    Ham, Mom = get_constraints_diagnostic(
        initial_state_2d.flatten(), 0.0, grid, background, hydro
    )

    # Ham shape: [1, N] (1 time, N spatial points)
    Ham = Ham[0, :]  # Extract 1D array

    # ========================================================================
    # DEFINE REGIONS FOR ANALYSIS (CRITICAL - exclude ghosts)
    # ========================================================================

    # Interior region (excludes ghosts)
    interior = slice(NUM_GHOSTS, -NUM_GHOSTS)
    r_interior = grid.r[interior]
    Ham_interior = Ham[interior]

    # Deep interior region (well inside star, away from surface and ghosts)
    deep_interior_mask = (r_interior > r_interior[0]) & (r_interior < 0.9 * R)
    Ham_deep = Ham_interior[deep_interior_mask]
    r_deep = r_interior[deep_interior_mask]

    # Near surface region
    surface_mask = (r_interior >= 0.9 * R) & (r_interior <= 1.1 * R)
    Ham_surface = Ham_interior[surface_mask]

    # Exterior region (vacuum)
    exterior_mask = r_interior > 1.1 * R
    Ham_exterior = Ham_interior[exterior_mask]

    # ========================================================================
    # COMPUTE ERROR METRICS
    # ========================================================================

    # Maximum in deep interior
    max_Ham_deep = np.max(np.abs(Ham_deep))
    i_max_deep = np.argmax(np.abs(Ham_deep))
    r_max_Ham = r_deep[i_max_deep]

    # L2 norm in interior
    L2_Ham = np.sqrt(np.mean(Ham_deep**2))

    # Maximum in exterior (should be ~0)
    max_Ham_exterior = np.max(np.abs(Ham_exterior)) if len(Ham_exterior) > 0 else 0.0

    # Maximum near surface
    max_Ham_surface = np.max(np.abs(Ham_surface)) if len(Ham_surface) > 0 else 0.0

    # ========================================================================
    # DETAILED DIAGNOSTIC OUTPUT
    # ========================================================================

    print("\n" + "="*70)
    print("HAMILTONIAN CONSTRAINT ANALYSIS")
    print("="*70)

    print(f"\nRegion statistics:")
    print(f"  Deep interior: {len(Ham_deep)} points (r < 0.9R)")
    print(f"  Surface:       {len(Ham_surface)} points (0.9R < r < 1.1R)")
    print(f"  Exterior:      {len(Ham_exterior)} points (r > 1.1R)")

    print(f"\nHamiltonian constraint (deep interior, r < 0.9R):")
    print(f"  max|Ham| = {max_Ham_deep:.6e} at r = {r_max_Ham:.6f}")
    print(f"  L2(Ham)  = {L2_Ham:.6e}")

    print(f"\nHamiltonian constraint (near surface, 0.9R < r < 1.1R):")
    print(f"  max|Ham| = {max_Ham_surface:.6e}")

    print(f"\nHamiltonian constraint (exterior, r > 1.1R):")
    print(f"  max|Ham| = {max_Ham_exterior:.6e}")

    # If constraint is violated, show radial profile
    if max_Ham_deep > 0.1:
        print(f"\n" + "⚠"*35)
        print("WARNING: LARGE CONSTRAINT VIOLATION DETECTED!")
        print("⚠"*35)

        print(f"\nRadial profile of |Ham| (first 10 interior points):")
        print(f"{'i':>4s} {'r':>10s} {'Ham':>15s} {'|Ham|':>15s}")
        print("-"*50)
        for idx in range(NUM_GHOSTS, NUM_GHOSTS+10):
            print(f"{idx:4d} {grid.r[idx]:10.6f} {Ham[idx]:+15.6e} {abs(Ham[idx]):15.6e}")

        print(f"\nRadial profile around maximum (±5 points):")
        i_max_abs = NUM_GHOSTS + np.argmax(np.abs(Ham_interior))
        i_start = max(NUM_GHOSTS, i_max_abs - 5)
        i_end = min(grid.N - NUM_GHOSTS, i_max_abs + 6)
        print(f"{'i':>4s} {'r':>10s} {'Ham':>15s} {'|Ham|':>15s}")
        print("-"*50)
        for idx in range(i_start, i_end):
            marker = " ← MAX" if idx == i_max_abs else ""
            print(f"{idx:4d} {grid.r[idx]:10.6f} {Ham[idx]:+15.6e} {abs(Ham[idx]):15.6e}{marker}")

    # ========================================================================
    # ASSERTIONS
    # ========================================================================

    # Tolerance: allow for truncation errors and interpolation artifacts
    tolerance_deep = 0.1      # Interior: relatively generous
    tolerance_exterior = 1e-10  # Exterior: should be exact (vacuum)

    # Check deep interior
    assert max_Ham_deep < tolerance_deep, \
        (f"Hamiltonian constraint violated in deep interior:\n"
         f"  max|Ham| = {max_Ham_deep:.3e} > tolerance {tolerance_deep}\n"
         f"  at r = {r_max_Ham:.6f}\n"
         f"  This indicates problems in TOV initial data construction.")

    assert L2_Ham < tolerance_deep, \
        (f"Hamiltonian L2 norm too large:\n"
         f"  L2(Ham) = {L2_Ham:.3e} > tolerance {tolerance_deep}\n"
         f"  This indicates systematic constraint violation in interior.")

    # Check exterior (vacuum)
    if len(Ham_exterior) > 0:
        assert max_Ham_exterior < tolerance_exterior, \
            (f"Hamiltonian constraint violated in exterior (vacuum):\n"
             f"  max|Ham| = {max_Ham_exterior:.3e} > tolerance {tolerance_exterior}\n"
             f"  Schwarzschild vacuum should satisfy Ham = 0 exactly.")

    # ========================================================================
    # SUCCESS
    # ========================================================================

    print("\n" + "="*70)
    print("✅ TEST PASSED: Hamiltonian constraint satisfied in initial data")
    print("="*70)
    print(f"\nSummary:")
    print(f"  Deep interior: max|Ham| = {max_Ham_deep:.3e} < {tolerance_deep}")
    print(f"  Deep interior: L2(Ham)  = {L2_Ham:.3e} < {tolerance_deep}")
    if len(Ham_exterior) > 0:
        print(f"  Exterior:      max|Ham| = {max_Ham_exterior:.3e} < {tolerance_exterior}")
    print("\nInitial data is physically consistent and ready for evolution.")
    print("="*70 + "\n")


if __name__ == "__main__":
    # Run test standalone
    test_tov_initial_hamiltonian_constraint()
