"""
Plot TOV Evolution Data

This script reads HDF5 files generated by TOVEvolution.py and creates
three videos showing the evolution of:
1. Conservative variables (D, Sr, tau) vs r
2. Primitive variables (rho0, p, vr, W) vs r
3. Time series (rho_central, l1_rho_error) vs t

Usage:
    python plot_TOVEvolution.py <data_directory>

Example:
    python plot_TOVEvolution.py tov_evolution_data2
"""

import numpy as np
import h5py
import json
import os
import sys
import matplotlib.pyplot as plt
import matplotlib.animation as animation
from matplotlib.gridspec import GridSpec
from glob import glob

# Check for available video writers
VIDEO_WRITER = 'pillow'  # Default to GIF (always available)
VIDEO_EXT = '.gif'

try:
    # Try to import ffmpeg writer
    from matplotlib.animation import FFMpegWriter
    # Check if ffmpeg is actually available
    import subprocess
    try:
        subprocess.run(['ffmpeg', '-version'], capture_output=True, check=True)
        VIDEO_WRITER = 'ffmpeg'
        VIDEO_EXT = '.mp4'
        print("Using ffmpeg for video output (MP4)")
    except (subprocess.CalledProcessError, FileNotFoundError):
        print("ffmpeg not found. Using pillow for GIF output")
except ImportError:
    print("FFMpegWriter not available. Using pillow for GIF output")

# Create output directory for plots
PLOTS_DIR = '/home/yo/repositories/engrenage/examples/TOV/plots/tov_evolution_data2/plots'


def find_latest_data_directory(base_dir='.'):
    """Find the latest TOV evolution data directory."""
    pattern = os.path.join(base_dir, 'tov_evolution_data*')
    dirs = glob(pattern)
    if not dirs:
        return None
    # Sort by modification time
    dirs.sort(key=lambda x: os.path.getmtime(x), reverse=True)
    return dirs[0]


def load_metadata(data_dir):
    """Load simulation metadata."""
    pattern = os.path.join(data_dir, 'tov_metadata_*.json')
    metadata_files = glob(pattern)
    if not metadata_files:
        raise FileNotFoundError(f"No metadata file found in {data_dir}")

    # Use the most recent metadata file
    metadata_file = sorted(metadata_files)[-1]

    with open(metadata_file, 'r') as f:
        metadata = json.load(f)

    print(f"Loaded metadata from: {metadata_file}")
    return metadata


def load_snapshot_data(data_dir):
    """Load all snapshot data from HDF5 file."""
    pattern = os.path.join(data_dir, 'tov_snapshots_*.h5')
    snapshot_files = glob(pattern)
    if not snapshot_files:
        raise FileNotFoundError(f"No snapshot file found in {data_dir}")

    snapshot_file = sorted(snapshot_files)[-1]

    print(f"Loading snapshots from: {snapshot_file}")

    snapshots = []
    with h5py.File(snapshot_file, 'r') as f:
        # Get grid
        r = f['grid/r'][:]

        # Get all snapshot names and sort them
        snap_names = sorted([k for k in f['snapshots'].keys()],
                           key=lambda x: int(x.split('_')[1]))

        print(f"Found {len(snap_names)} snapshots")

        for snap_name in snap_names:
            snap = f['snapshots'][snap_name]

            snapshot_data = {
                'step': snap.attrs['step'],
                'time': snap.attrs['time'],
                'r': r,
                'D': snap['conservatives/D'][:],
                'Sr': snap['conservatives/Sr'][:],
                'tau': snap['conservatives/tau'][:],
            }

            # Load primitives if available
            if 'primitives' in snap:
                snapshot_data['rho0'] = snap['primitives/rho0'][:]
                snapshot_data['p'] = snap['primitives/p'][:]
                snapshot_data['vr'] = snap['primitives/vr'][:]
                snapshot_data['W'] = snap['primitives/W'][:]

            snapshots.append(snapshot_data)

    return snapshots


def load_evolution_data(data_dir):
    """Load evolution time series from HDF5 file."""
    pattern = os.path.join(data_dir, 'tov_evolution_*.h5')
    evolution_files = glob(pattern)
    if not evolution_files:
        print("Warning: No evolution file found")
        return None

    evolution_file = sorted(evolution_files)[-1]

    print(f"Loading evolution data from: {evolution_file}")

    evolution = {}
    with h5py.File(evolution_file, 'r') as f:
        for key in f.keys():
            evolution[key] = f[key][:]

    return evolution


def create_conservative_video(snapshots, R_star, output_dir):
    """Create video of conservative variables evolution."""
    print("\nCreating conservative variables video...")

    fig = plt.figure(figsize=(10, 12))
    gs = GridSpec(3, 1, figure=fig, hspace=0.35, top=0.93)

    ax1 = fig.add_subplot(gs[0, 0])
    ax2 = fig.add_subplot(gs[1, 0])
    ax3 = fig.add_subplot(gs[2, 0])

    r = snapshots[0]['r']

    # Initialize lines
    line_D, = ax1.semilogy([], [], 'b-', linewidth=2, label='D')
    vline_D = ax1.axvline(R_star, color='gray', linestyle='--', linewidth=1.5,
                          alpha=0.7, label=f'R*={R_star:.3f}')
    ax1.set_xlabel('r [M]', fontsize=11)
    ax1.set_ylabel('D', fontsize=11)
    ax1.set_title('Conserved Density', fontsize=12, fontweight='bold')
    ax1.grid(True, alpha=0.3)
    ax1.legend(loc='upper right')
    ax1.set_xlim(r[0], r[-1])

    line_Sr, = ax2.plot([], [], 'r-', linewidth=2, label='Sr')
    vline_Sr = ax2.axvline(R_star, color='gray', linestyle='--', linewidth=1.5,
                           alpha=0.7, label=f'R*={R_star:.3f}')
    ax2.set_xlabel('r [M]', fontsize=11)
    ax2.set_ylabel('Sr', fontsize=11)
    ax2.set_title('Conserved Radial Momentum', fontsize=12, fontweight='bold')
    ax2.grid(True, alpha=0.3)
    ax2.legend(loc='upper right')
    ax2.set_xlim(r[0], r[-1])

    line_tau, = ax3.semilogy([], [], 'g-', linewidth=2, label='tau')
    vline_tau = ax3.axvline(R_star, color='gray', linestyle='--', linewidth=1.5,
                            alpha=0.7, label=f'R*={R_star:.3f}')
    ax3.set_xlabel('r [M]', fontsize=11)
    ax3.set_ylabel('tau', fontsize=11)
    ax3.set_title('Conserved Energy', fontsize=12, fontweight='bold')
    ax3.grid(True, alpha=0.3)
    ax3.legend(loc='upper right')
    ax3.set_xlim(r[0], r[-1])

    # Compute y-limits from all snapshots
    D_min, D_max = 1e10, -1e10
    Sr_min, Sr_max = 1e10, -1e10
    tau_min, tau_max = 1e10, -1e10

    for snap in snapshots:
        D_min = min(D_min, np.min(snap['D'][snap['D'] > 0]))
        D_max = max(D_max, np.max(snap['D']))
        Sr_min = min(Sr_min, np.min(snap['Sr']))
        Sr_max = max(Sr_max, np.max(snap['Sr']))
        tau_pos = snap['tau'][snap['tau'] > 0]
        if len(tau_pos) > 0:
            tau_min = min(tau_min, np.min(tau_pos))
        tau_max = max(tau_max, np.max(np.abs(snap['tau'])))

    ax1.set_ylim(D_min * 0.5, D_max * 2.0)
    ax2.set_ylim(Sr_min * 1.2, Sr_max * 1.2)
    ax3.set_ylim(tau_min * 0.5, tau_max * 2.0)

    # Time text using suptitle
    time_text = fig.suptitle('', fontsize=14, fontweight='bold', y=0.98)

    def init():
        line_D.set_data([], [])
        line_Sr.set_data([], [])
        line_tau.set_data([], [])
        time_text.set_text('')
        return line_D, line_Sr, line_tau, time_text

    def animate(i):
        snap = snapshots[i]

        line_D.set_data(snap['r'], snap['D'])
        line_Sr.set_data(snap['r'], snap['Sr'])
        line_tau.set_data(snap['r'], np.abs(snap['tau']))

        time_text.set_text(f"t = {snap['time']:.4f} M")

        return line_D, line_Sr, line_tau, time_text

    anim = animation.FuncAnimation(fig, animate, init_func=init,
                                   frames=len(snapshots), interval=50, blit=False)

    output_file = os.path.join(output_dir, f'conservative_evolution{VIDEO_EXT}')
    anim.save(output_file, writer=VIDEO_WRITER, fps=20, dpi=150)
    print(f"Saved: {output_file}")
    plt.close(fig)


def create_primitive_video(snapshots, R_star, output_dir):
    """Create video of primitive variables evolution."""
    print("\nCreating primitive variables video...")

    # Check if primitives are available
    if 'rho0' not in snapshots[0]:
        print("Warning: Primitive variables not found in snapshots. Skipping primitive video.")
        return

    fig = plt.figure(figsize=(14, 10))
    gs = GridSpec(2, 2, figure=fig, hspace=0.35, wspace=0.3, top=0.93)

    ax1 = fig.add_subplot(gs[0, 0])  # rho0
    ax2 = fig.add_subplot(gs[0, 1])  # p
    ax3 = fig.add_subplot(gs[1, 0])  # vr
    ax4 = fig.add_subplot(gs[1, 1])  # W

    r = snapshots[0]['r']

    # Initialize lines for rho0
    line_rho, = ax1.semilogy([], [], 'b-', linewidth=2, label='rho0')
    vline_rho = ax1.axvline(R_star, color='gray', linestyle='--', linewidth=1.5,
                            alpha=0.7, label=f'R*={R_star:.3f}')
    ax1.set_xlabel('r [M]', fontsize=11)
    ax1.set_ylabel(r'$\rho_0$', fontsize=11)
    ax1.set_title('Baryon Density', fontsize=12, fontweight='bold')
    ax1.grid(True, alpha=0.3)
    ax1.legend(loc='upper right')
    ax1.set_xlim(r[0], r[-1])

    # Initialize lines for p
    line_p, = ax2.semilogy([], [], 'r-', linewidth=2, label='P')
    vline_p = ax2.axvline(R_star, color='gray', linestyle='--', linewidth=1.5,
                          alpha=0.7, label=f'R*={R_star:.3f}')
    ax2.set_xlabel('r [M]', fontsize=11)
    ax2.set_ylabel('P', fontsize=11)
    ax2.set_title('Pressure', fontsize=12, fontweight='bold')
    ax2.grid(True, alpha=0.3)
    ax2.legend(loc='upper right')
    ax2.set_xlim(r[0], r[-1])

    # Initialize lines for vr
    line_vr, = ax3.plot([], [], 'g-', linewidth=2, label='vr')
    vline_vr = ax3.axvline(R_star, color='gray', linestyle='--', linewidth=1.5,
                           alpha=0.7, label=f'R*={R_star:.3f}')
    ax3.set_xlabel('r [M]', fontsize=11)
    ax3.set_ylabel(r'$v^r$', fontsize=11)
    ax3.set_title('Radial Velocity', fontsize=12, fontweight='bold')
    ax3.grid(True, alpha=0.3)
    ax3.legend(loc='upper right')
    ax3.set_xlim(r[0], r[-1])

    # Initialize lines for W
    line_W, = ax4.plot([], [], 'm-', linewidth=2, label='W')
    vline_W = ax4.axvline(R_star, color='gray', linestyle='--', linewidth=1.5,
                          alpha=0.7, label=f'R*={R_star:.3f}')
    ax4.set_xlabel('r [M]', fontsize=11)
    ax4.set_ylabel('W', fontsize=11)
    ax4.set_title('Lorentz Factor', fontsize=12, fontweight='bold')
    ax4.grid(True, alpha=0.3)
    ax4.legend(loc='upper right')
    ax4.set_xlim(r[0], r[-1])

    # Compute y-limits from all snapshots
    rho_min, rho_max = 1e10, -1e10
    p_min, p_max = 1e10, -1e10
    vr_min, vr_max = 1e10, -1e10
    W_min, W_max = 1e10, -1e10

    for snap in snapshots:
        rho_pos = snap['rho0'][snap['rho0'] > 0]
        if len(rho_pos) > 0:
            rho_min = min(rho_min, np.min(rho_pos))
            rho_max = max(rho_max, np.max(rho_pos))

        p_pos = snap['p'][snap['p'] > 0]
        if len(p_pos) > 0:
            p_min = min(p_min, np.min(p_pos))
            p_max = max(p_max, np.max(p_pos))

        vr_min = min(vr_min, np.min(snap['vr']))
        vr_max = max(vr_max, np.max(snap['vr']))

        W_min = min(W_min, np.min(snap['W']))
        W_max = max(W_max, np.max(snap['W']))

    ax1.set_ylim(rho_min * 0.5, rho_max * 2.0)
    ax2.set_ylim(p_min * 0.5, p_max * 2.0)
    ax3.set_ylim(vr_min * 1.2, vr_max * 1.2)
    ax4.set_ylim(W_min * 0.95, W_max * 1.05)

    # Time text using suptitle
    time_text = fig.suptitle('', fontsize=14, fontweight='bold', y=0.98)

    def init():
        line_rho.set_data([], [])
        line_p.set_data([], [])
        line_vr.set_data([], [])
        line_W.set_data([], [])
        time_text.set_text('')
        return line_rho, line_p, line_vr, line_W, time_text

    def animate(i):
        snap = snapshots[i]

        line_rho.set_data(snap['r'], np.maximum(snap['rho0'], 1e-20))
        line_p.set_data(snap['r'], np.maximum(snap['p'], 1e-20))
        line_vr.set_data(snap['r'], snap['vr'])
        line_W.set_data(snap['r'], snap['W'])

        time_text.set_text(f"t = {snap['time']:.4f} M")

        return line_rho, line_p, line_vr, line_W, time_text

    anim = animation.FuncAnimation(fig, animate, init_func=init,
                                   frames=len(snapshots), interval=50, blit=False)

    output_file = os.path.join(output_dir, f'primitive_evolution{VIDEO_EXT}')
    anim.save(output_file, writer=VIDEO_WRITER, fps=20, dpi=150)
    print(f"Saved: {output_file}")
    plt.close(fig)


def create_timeseries_video(evolution, snapshots, output_dir):
    """Create video of time series evolution (rho_central, l1_rho_error)."""
    print("\nCreating time series video...")

    if evolution is None:
        print("Warning: Evolution data not available. Skipping time series video.")
        return

    fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(12, 8))

    time = evolution['time']
    rho_c = evolution['rho_central']
    l1_err = evolution['l1_rho_error']

    # Initialize lines
    line_rho_c, = ax1.plot([], [], 'b-', linewidth=2, label=r'$\rho_c(t)$')
    point_rho_c, = ax1.plot([], [], 'ro', markersize=8, label='Current')
    ax1.set_xlabel('Time t [M]', fontsize=11)
    ax1.set_ylabel(r'$\rho_c$', fontsize=11)
    ax1.set_title('Central Density Evolution', fontsize=12, fontweight='bold')
    ax1.grid(True, alpha=0.3)
    ax1.legend(loc='upper right')
    ax1.set_xlim(time[0], time[-1])
    ax1.set_ylim(np.min(rho_c) * 0.95, np.max(rho_c) * 1.05)

    line_l1, = ax2.semilogy([], [], 'r-', linewidth=2, label=r'$L_1$ error')
    point_l1, = ax2.semilogy([], [], 'ro', markersize=8, label='Current')
    ax2.set_xlabel('Time t [M]', fontsize=11)
    ax2.set_ylabel(r'$\|\Delta\rho\|_1 / \|\rho_0\|_1$', fontsize=11)
    ax2.set_title('L1 Density Error Evolution', fontsize=12, fontweight='bold')
    ax2.grid(True, alpha=0.3, which='both')
    ax2.legend(loc='upper right')
    ax2.set_xlim(time[0], time[-1])
    ax2.set_ylim(np.min(l1_err[l1_err > 0]) * 0.5, np.max(l1_err) * 2.0)

    plt.tight_layout(rect=[0, 0, 1, 0.93])

    # Time text using suptitle
    time_text = fig.suptitle('', fontsize=14, fontweight='bold', y=0.98)

    # Create step-to-index mapping
    step_to_idx = {int(evolution['step'][i]): i for i in range(len(evolution['step']))}

    def init():
        line_rho_c.set_data([], [])
        point_rho_c.set_data([], [])
        line_l1.set_data([], [])
        point_l1.set_data([], [])
        time_text.set_text('')
        return line_rho_c, point_rho_c, line_l1, point_l1, time_text

    def animate(i):
        snap = snapshots[i]
        current_step = snap['step']

        # Find the corresponding index in evolution data
        if current_step in step_to_idx:
            idx = step_to_idx[current_step]

            # Plot up to current time
            line_rho_c.set_data(time[:idx+1], rho_c[:idx+1])
            point_rho_c.set_data([time[idx]], [rho_c[idx]])

            line_l1.set_data(time[:idx+1], l1_err[:idx+1])
            point_l1.set_data([time[idx]], [l1_err[idx]])

            time_text.set_text(f"t = {snap['time']:.4f} M")

        return line_rho_c, point_rho_c, line_l1, point_l1, time_text

    anim = animation.FuncAnimation(fig, animate, init_func=init,
                                   frames=len(snapshots), interval=50, blit=False)

    output_file = os.path.join(output_dir, f'timeseries_evolution{VIDEO_EXT}')
    anim.save(output_file, writer=VIDEO_WRITER, fps=20, dpi=150)
    print(f"Saved: {output_file}")
    plt.close(fig)


def main():
    """Main function."""
    print("="*70)
    print("TOV Evolution Video Generator")
    print("="*70)

    # Get data directory
    if len(sys.argv) > 1:
        data_dir = sys.argv[1]
    else:
        # Use tov_evolution_data2 by default
        data_dir = '/home/yo/repositories/engrenage/examples/TOV/plots/tov_evolution_data2'
        print(f"Using default data directory: {data_dir}")

    if not os.path.exists(data_dir):
        print(f"Error: Directory '{data_dir}' does not exist.")
        sys.exit(1)

    # Create output directory
    output_dir = os.path.join(data_dir, PLOTS_DIR)
    os.makedirs(output_dir, exist_ok=True)
    print(f"Output directory: {output_dir}\n")

    # Load data
    metadata = load_metadata(data_dir)
    snapshots = load_snapshot_data(data_dir)
    evolution = load_evolution_data(data_dir)

    # Get stellar radius from metadata
    R_star = metadata['tov_solution']['R']
    print(f"\nStellar radius R* = {R_star:.6f}")

    # Create videos
    print("\n" + "="*70)
    print("Creating videos...")
    print("="*70)

    create_conservative_video(snapshots, R_star, output_dir)
    create_primitive_video(snapshots, R_star, output_dir)
    create_timeseries_video(evolution, snapshots, output_dir)

    print("\n" + "="*70)
    print("All videos created successfully!")
    print(f"Videos saved in: {output_dir}")
    print("="*70)


if __name__ == "__main__":
    main()
